In [1]:
# Creating Numpy Arrays: n-d arrays

In [8]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])

In [4]:
type(arr1)

numpy.ndarray

In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr3 = np.zeros((2,3))

In [11]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr4 = np.ones((4,5))

In [13]:
arr4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
arr_a = np.full((3,4),0.11)

In [4]:
arr_a

array([[0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11]])

In [10]:
np.empty((2,3)) # To create an uninitialised array with a given shape. 
                # Its content is not predictable.

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
arr5 = np.identity(5)

In [15]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
arr6 = np.arange(5,16,2)

In [21]:
arr6

array([ 5,  7,  9, 11, 13, 15])

In [22]:
arr7 = np.linspace(5,50,25)

In [23]:
arr7

array([ 5.   ,  6.875,  8.75 , 10.625, 12.5  , 14.375, 16.25 , 18.125,
       20.   , 21.875, 23.75 , 25.625, 27.5  , 29.375, 31.25 , 33.125,
       35.   , 36.875, 38.75 , 40.625, 42.5  , 44.375, 46.25 , 48.125,
       50.   ])

In [24]:
arr8 = arr7.copy()

In [25]:
arr8

array([ 5.   ,  6.875,  8.75 , 10.625, 12.5  , 14.375, 16.25 , 18.125,
       20.   , 21.875, 23.75 , 25.625, 27.5  , 29.375, 31.25 , 33.125,
       35.   , 36.875, 38.75 , 40.625, 42.5  , 44.375, 46.25 , 48.125,
       50.   ])