In [1]:
# faster, convinient, less memory -> numpy arrays

In [3]:
import numpy as np

In [3]:
lista = range(100)
arr11 = np.arange(100)

In [4]:
import sys

In [5]:
print(sys.getsizeof(87)*len(lista))

2800


In [6]:
print(arr11.itemsize * arr11.size)

400


In [7]:
import time

In [13]:
x = range(100000000)
y = range(100000000,200000000)

start_time = time.time()
z = [x+y for (x,y) in zip(x,y)]
print(time.time()-start_time)

21.06165099143982


In [14]:
a = np.arange(100000000)
b = np.arange(100000000,200000000)

start_time = time.time()
c = a+b
print(time.time()-start_time)

2.035846710205078


In [1]:
# If you assign a single value to an ndarray slice, it is copied
# across the whole slice

In [4]:
a = np.array([1, 2, 5, 7, 8])

In [5]:
a[1:3] = -1

In [6]:
a

array([ 1, -1, -1,  7,  8])

In [7]:
# ndarray slices are actually views on the same data buffer. If
# you modify it, it is going to modify the original ndarray as well.

In [13]:
a = np.array([1, 2, 5, 7, 8])

In [14]:
a

array([1, 2, 5, 7, 8])

In [15]:
a_slice = a[1:5]
a_slice[1] = 1000

In [16]:
a

array([   1,    2, 1000,    7,    8])

In [17]:
# If you want a copy of the data, you need to use the copy
# method as

In [18]:
another_slice = a[2:6].copy()

In [20]:
another_slice[1] = 0 # modify
another_slice

array([1000,    0,    8])

In [21]:
a  # remains unchanged

array([   1,    2, 1000,    7,    8])