In [3]:
import numpy as np

In [4]:
arr12 = np.arange(24).reshape(6,4)

In [5]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
arr12[2]     # gives 3rd row

array([ 8,  9, 10, 11])

In [7]:
arr12[:,2]    # gives 3rd column

array([ 2,  6, 10, 14, 18, 22])

In [8]:
arr12[:,1:3]   # gives 2nd and 3rd column

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [9]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [10]:
# iterations

In [11]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [13]:
for i in np.nditer(arr12):    # iterate all elements in nd array
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [14]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
arr12[2][3]     # indexing

11

In [1]:
# Indexing 1-d array

In [5]:
a = np.arange(10)

In [6]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a[3]

3

In [8]:
a[2:5]  # range

array([2, 3, 4])

In [9]:
a[2::2]  # row::how many jumps

array([2, 4, 6, 8])

In [10]:
a[::-1]  # go in reverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])