In [4]:
import numpy as np

In [11]:
# Ravel - it will make nd arrays to 1-d arrays

In [40]:
arr4 = np.arange(6,12).reshape(3,2)

In [41]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [10]:
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [2]:
# Reshape

In [ ]:
# Reshaping a numpy array when the desired number of columns is known, 
# but the desired number of rows is unknown

In [18]:
my_arr = np.arange(9)
print(my_arr)

[0 1 2 3 4 5 6 7 8]


In [17]:
my_arr.reshape(-1,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
my_arr.reshape(3,-1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
# Transpose

In [42]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [51]:
arr4 = arr4.transpose()  # or arr4.T

In [29]:
# Stacking

In [30]:
arr3 = np.arange(6).reshape(2,3)
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
np.hstack((arr4,arr3))

array([[ 6,  8, 10,  0,  1,  2],
       [ 7,  9, 11,  3,  4,  5]])

In [32]:
np.vstack((arr3,arr4))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  8, 10],
       [ 7,  9, 11]])

In [ ]:
# Splitting

In [35]:
np.hsplit(arr3,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [36]:
np.vsplit(arr3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [1]:
# resizing arrays - used to create a new array of
# different sizes and dimensions

In [2]:
# syntax -> ndarray.resize(new_shape, refcheck=True)

In [11]:
my_arr = np.array([ [0,1], [2,3] ])

In [12]:
my_arr # ValueError: cannot resize an array that references or is referenced ...
#Unless refcheck is False:

array([[0, 1],
       [2, 3]])

In [14]:
my_arr.resize( (2, 3) ,refcheck=False)

In [15]:
my_arr

array([[0, 1, 2],
       [3, 0, 0]])