In [1]:
import numpy as np

In [2]:
arr8 = np.arange(24).reshape(6,4)

In [3]:
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
arr8[[0,2,4]]  # index the rows in a list

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [6]:
arr = np.random.randint(low=1,high=100,size=20).reshape(4,5)

In [7]:
arr

array([[86, 45, 93, 22, 19],
       [64, 72, 15, 93, 67],
       [95, 84, 40, 67, 69],
       [26, 77, 75,  5, 73]])

In [12]:
arr>50

array([[ True, False,  True, False, False],
       [ True,  True, False,  True,  True],
       [ True,  True, False,  True,  True],
       [False,  True,  True, False,  True]])

In [ ]:
# Indexing using boolean arrays

In [11]:
arr[(arr>50) & (arr%2==1)]  # we use bitwise logical operators on boolean

array([93, 93, 67, 95, 67, 69, 77, 75, 73])

In [13]:
arr[(arr>50) & (arr%2==1)] = 0

In [14]:
arr

array([[86, 45,  0, 22, 19],
       [64, 72, 15,  0,  0],
       [ 0, 84, 40,  0,  0],
       [26,  0,  0,  5,  0]])

In [15]:
a = np.arange(12).reshape(3, 4)

In [16]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
rows_on = np.array([ True, False, True])

In [18]:
a[rows_on,:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [20]:
a[[0,2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])