In [2]:
import numpy as np

In [3]:
# same size arrays
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [4]:
# one element with an array -> 1x1 with nxm
a = np.array([1.0, 2.0, 3.0])
b = [2.0]
a * b

array([2., 4., 6.])

In [5]:
"""
Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3
"""

'\nImage  (3d array): 256 x 256 x 3\nScale  (1d array):             3\nResult (3d array): 256 x 256 x 3\n'

In [6]:
"""
A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5
"""

'\nA      (4d array):  8 x 1 x 6 x 1\nB      (3d array):      7 x 1 x 5\nResult (4d array):  8 x 7 x 6 x 5\n'

In [15]:
a = np.array([0.0, 10.0, 20.0]).reshape(1,3)
b = np.array([1.0, 2.0, 3.0]).reshape(3,1)

In [16]:
a+b

array([[ 1., 11., 21.],
       [ 2., 12., 22.],
       [ 3., 13., 23.]])