In [1]:
import numpy as np

In [2]:
# random module   

In [8]:
np.random.random() # new random value from 0 to 1 for every run

0.6336482349262754

In [6]:
np.random.seed(10)  # same random value b/w 0 to 1 for every run
np.random.random()

0.771320643266746

In [ ]:
# to get an array of random numbers

In [16]:
a=np.random.uniform(1,100,10)  #random value in float b/w start,end,nof ele

In [17]:
b=np.random.randint(1,100,10)   #random value in int b/w start,end,nof ele

In [66]:
np.random.rand(2,3)            # ndarray of random float values b/w 0 - 1 

array([[0.31827281, 0.51979699, 0.57813643],
       [0.85393375, 0.06809727, 0.46453081]])

In [18]:
np.min(b)

41

In [20]:
np.argmin(b)   # gives the index of min in array

9

In [22]:
arr = np.random.randint(1,10,6)

In [24]:
arr[arr%2 == 1] = -1

In [25]:
arr

array([ 6, -1, -1,  8,  4, -1])

In [26]:
# Now if we donot want to replace the array itself

In [27]:
# where(condition,True-st,False-st)

In [40]:
arr = np.random.randint(1,10,6)

In [41]:
arr

array([3, 6, 1, 2, 1, 2])

In [42]:
new_arr = np.where(arr%2==1,-1,arr)

In [43]:
new_arr

array([-1,  6, -1,  2, -1,  2])

In [44]:
arr

array([3, 6, 1, 2, 1, 2])

In [ ]:
#sorting

In [58]:
arr2 = np.random.randint(1,100,10)

In [59]:
arr2

array([28, 83, 63, 78, 49, 94, 76, 87, 38, 12])

In [60]:
new_arr2 = np.sort(arr2)   # sorting the array from low to high

In [61]:
arr2

array([28, 83, 63, 78, 49, 94, 76, 87, 38, 12])

In [62]:
new_arr2

array([12, 28, 38, 49, 63, 76, 78, 83, 87, 94])

In [63]:
new_arr2.size

10

In [64]:
#'n' percentile-to get a value which is >= n% values in the list

In [65]:
np.percentile(new_arr2,50) # -> np.percentile(array,n) -> n percentile

69.5

In [67]:
# solving a system of linear scalar equations

In [80]:
coeffs = np.array([[2,6],[5,3]])
depvars = np.array([6,-9])

In [85]:
solution = np.linalg.solve(coeffs,depvars)

In [86]:
solution

array([-3.,  2.])

In [87]:
coeffs.dot(solution)

array([ 6., -9.])