In [10]:
# load data from csv files using numpy

In [12]:
import numpy as np

In [26]:
# np.loadtxt(fname,dtype=<class='float'>,comments='#',delimiter=None,
# converters=None,skiprows=0,usecols=None,unpack=false,ndim=0)
# skiprows-> skips the number of rows in file
# unpack = true -> stores the columns in seperate arrays
# usecols -> which columns to use from data

In [27]:
data = np.loadtxt('test.csv', dtype = float, delimiter = ',')

In [28]:
data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [29]:
#def load_housing_data(file = FILE ):
#    return np.loadtxt
#(file, dtype={'names': ('longitude','latitude','housing_median_age',
#'total_rooms','total_bedrooms','population','households','median_income',
#'median_house_value','ocean_proximity'),//->keys(columntags)
#'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')},
# -> data formats for each columns - 
# 'f8' means 64-bit floating-point number
# '|S15' -means a string of length of 15 characters
#delimiter=',', skiprows=1, unpack=True)
# https://numpy.org/doc/stable/reference/arrays.dtypes.html

In [30]:
"""
genfromtxt() function is very helpful when you are expecting some missing 
values in the dataset to be loaded. Below is a sample code

import numpy as np
my_arr = np.genfromtxt('my_file.txt',skip_header=2, filling_values=9999999)
"""

"\ngenfromtxt() function is very helpful when you are expecting some missing \nvalues in the dataset to be loaded. Below is a sample code\n\nimport numpy as np\nmy_arr = np.genfromtxt('my_file.txt',skip_header=2, filling_values=9999999)\n"

In [5]:
def generate_lines (filepath, delimiters=[]):
    with open (filepath) as fhand:
        text = []
        for line in fhand:
            line = line.strip()
            for d in delimiters:
                line = line.replace(d," ")
            yield line
            #text.append(line)
        #return text
        

In [7]:
gen = generate_lines("./test_del.csv",["-",","])
#for i in gen : print(i)
list(gen)

['110.90 146.03 3 7 1981', '44.83 211.82 1 2 1986', '97.13 209.30 14 2 1989']

In [124]:
data = np.loadtxt(gen,dtype="float,float,int,int,int",unpack = True)

[array([110.9 ,  44.83,  97.13]),
 array([146.03, 211.82, 209.3 ]),
 array([ 3,  1, 14]),
 array([7, 2, 2]),
 array([1981, 1986, 1989])]

In [ ]:
# genformtxt() ->takes care of missing values:-parameter: filling_values = 

In [ ]:
#def <<your code comes here>>(file =FILE ):
#    return np.genfromtxt(file, 
# dtype={'names': ('longitude','latitude','housing_median_age',
# 'total_rooms','total_bedrooms','population','households','median_income',
# 'median_house_value','ocean_proximity'),
# 'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')
# }, delimiter=',', skip_header=1, filling_values = 99999999, unpack=False)