In [3]:
import numpy as np

In [26]:
def calculate (lst):
    if len(lst) < 9:
        raise ValueError("List must contain nine numbers.")
    mat = np.array(lst).reshape(3,3)
    mean = [mat.mean(axis=0).tolist(),mat.mean(axis=1).tolist(),mat.mean().tolist()]
    var = [mat.var(axis=0).tolist(),mat.var(axis=1).tolist(),mat.var().tolist()]
    std = [mat.std(axis=0).tolist(),mat.std(axis=1).tolist(),mat.std().tolist()]
    max = [mat.max(axis=0).tolist(),mat.max(axis=1).tolist(),mat.max().tolist()]
    min = [mat.min(axis=0).tolist(),mat.min(axis=1).tolist(),mat.min().tolist()]
    sum = [mat.sum(axis=0).tolist(),mat.sum(axis=1).tolist(),mat.sum().tolist()]
    dict_r = {'mean':mean,'variance':var,'standard deviation':std,'max':max,'min':min,'sum':sum}
    return dict_r

In [27]:
calculate([0,1,2,3,4,5,6,7,8])

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6.0, 7.0, 8.0], [2.0, 5.0, 8.0], 8.0],
 'min': [[0.0, 1.0, 2.0], [0.0, 3.0, 6.0], 0.0],
 'sum': [[9.0, 12.0, 15.0], [3.0, 12.0, 21.0], 36.0]}

In [28]:
calculate([2,6,2,8,4,0,1,5])

ValueError: List must contain nine numbers.

In [29]:
calculate([2,6,2,8,4,0,1,5,7])

{'mean': [[3.6666666666666665, 5.0, 3.0],
  [3.3333333333333335, 4.0, 4.333333333333333],
  3.888888888888889],
 'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666],
  [3.555555555555556, 10.666666666666666, 6.222222222222221],
  6.987654320987654],
 'standard deviation': [[3.091206165165235,
   0.816496580927726,
   2.943920288775949],
  [1.8856180831641267, 3.265986323710904, 2.494438257849294],
  2.6434171674156266],
 'max': [[8.0, 6.0, 7.0], [6.0, 8.0, 7.0], 8.0],
 'min': [[1.0, 4.0, 0.0], [2.0, 0.0, 1.0], 0.0],
 'sum': [[11.0, 15.0, 9.0], [10.0, 12.0, 13.0], 35.0]}

In [22]:
calculate([9,1,5,3,3,3,2,9,0])

{'mean': [array([4.66666667, 4.33333333, 2.66666667]),
  array([5.        , 3.        , 3.66666667]),
  3.888888888888889],
 'variance': [array([ 9.55555556, 11.55555556,  4.22222222]),
  array([10.66666667,  0.        , 14.88888889]),
  9.209876543209875],
 'standard deviation': [array([3.09120617, 3.39934634, 2.05480467]),
  array([3.26598632, 0.        , 3.8586123 ]),
  3.0347778408328137],
 'max': [array([9, 9, 5]), array([9, 3, 9]), 9],
 'min': [array([2, 1, 0]), array([1, 3, 0]), 0],
 'sum': [array([14, 13,  8]), array([15,  9, 11]), 35]}